
    // this file was auto generated by python script
    // this icon was sourced from feather icons 4.2.8
    import React from 'react';
    const StopCircle = () => (
      <>
        <circle cx="12" cy="12" r="10"></circle><rect x="9" y="9" width="6" height="6"></rect>
      </>
    );
    export default StopCircle;
    