
    // this file was auto generated by python script
    // this icon was sourced from feather icons 4.2.8
    import React from 'react';
    const Play = () => (
      <>
        <polygon points="5 3 19 12 5 21 5 3"></polygon>
      </>
    );
    export default Play;
    