
    // this file was auto generated by python script
    // this icon was sourced from feather icons 4.2.8
    import React from 'react';
    const ChevronRight = () => (
      <>
        <polyline points="9 18 15 12 9 6"></polyline>
      </>
    );
    export default ChevronRight;
    