import peerDepsExternal from 'rollup-plugin-peer-deps-external';
import commonjs from '@rollup/plugin-commonjs';
import typescript from 'rollup-plugin-typescript2';
import copy from 'rollup-plugin-copy';
import scss from 'rollup-plugin-scss';
import autoprefixer from 'autoprefixer';
import postcss from 'postcss';
import fs from 'fs';
import CleanCss from 'clean-css';

export default {
  input: [
    'src/index.ts',
    'src/components/Icon/index.ts',
    'src/components/Carousel/index.ts',
    'src/components/AlertDialogue/index.ts',
    'src/components/Button/index.ts',
    'src/components/Form/index.ts',
    'src/components/Image/index.ts',
    'src/components/Landmark/index.ts',
    'src/components/Layout/index.ts',
    'src/components/Link/index.ts',
    'src/components/ProgressBar/index.ts',
    'src/components/NavigationBar/index.ts',
    'src/components/Table/index.ts',
    'src/components/TabList/index.ts',
    'src/components/Breadcrumbs/index.ts',
    'src/components/Typography/index.ts',
    'src/components/AutoComplete/index.ts',
    'src/components/Pagination/index.ts',
    'src/components/Review/index.ts',
    'src/components/Accordion/index.ts',
    'src/components/Alert/index.ts',

    // feather icons
    'src/components/Icon/Activity/index.ts',
    'src/components/Icon/Airplay/index.ts',
    'src/components/Icon/AlertCircle/index.ts',
    'src/components/Icon/AlertOctagon/index.ts',
    'src/components/Icon/AlertTriangle/index.ts',
    'src/components/Icon/AlignCenter/index.ts',
    'src/components/Icon/AlignJustify/index.ts',
    'src/components/Icon/AlignLeft/index.ts',
    'src/components/Icon/AlignRight/index.ts',
    'src/components/Icon/Anchor/index.ts',
    'src/components/Icon/Aperture/index.ts',
    'src/components/Icon/Archive/index.ts',
    'src/components/Icon/ArrowDownCircle/index.ts',
    'src/components/Icon/ArrowDownLeft/index.ts',
    'src/components/Icon/ArrowDownRight/index.ts',
    'src/components/Icon/ArrowDown/index.ts',
    'src/components/Icon/ArrowLeftCircle/index.ts',
    'src/components/Icon/ArrowLeft/index.ts',
    'src/components/Icon/ArrowRightCircle/index.ts',
    'src/components/Icon/ArrowRight/index.ts',
    'src/components/Icon/ArrowUpCircle/index.ts',
    'src/components/Icon/ArrowUpLeft/index.ts',
    'src/components/Icon/ArrowUpRight/index.ts',
    'src/components/Icon/ArrowUp/index.ts',
    'src/components/Icon/AtSign/index.ts',
    'src/components/Icon/Award/index.ts',
    'src/components/Icon/BarChart2/index.ts',
    'src/components/Icon/BarChart/index.ts',
    'src/components/Icon/BatteryCharging/index.ts',
    'src/components/Icon/Battery/index.ts',
    'src/components/Icon/BellOff/index.ts',
    'src/components/Icon/Bell/index.ts',
    'src/components/Icon/Bluetooth/index.ts',
    'src/components/Icon/Bold/index.ts',
    'src/components/Icon/BookOpen/index.ts',
    'src/components/Icon/Book/index.ts',
    'src/components/Icon/Bookmark/index.ts',
    'src/components/Icon/Box/index.ts',
    'src/components/Icon/Briefcase/index.ts',
    'src/components/Icon/Calendar/index.ts',
    'src/components/Icon/CameraOff/index.ts',
    'src/components/Icon/Camera/index.ts',
    'src/components/Icon/Cast/index.ts',
    'src/components/Icon/CheckCircle/index.ts',
    'src/components/Icon/CheckSquare/index.ts',
    'src/components/Icon/Check/index.ts',
    'src/components/Icon/ChevronDown/index.ts',
    'src/components/Icon/ChevronLeft/index.ts',
    'src/components/Icon/ChevronRight/index.ts',
    'src/components/Icon/ChevronUp/index.ts',
    'src/components/Icon/ChevronsDown/index.ts',
    'src/components/Icon/ChevronsLeft/index.ts',
    'src/components/Icon/ChevronsRight/index.ts',
    'src/components/Icon/ChevronsUp/index.ts',
    'src/components/Icon/Chrome/index.ts',
    'src/components/Icon/Circle/index.ts',
    'src/components/Icon/Clipboard/index.ts',
    'src/components/Icon/Clock/index.ts',
    'src/components/Icon/CloudDrizzle/index.ts',
    'src/components/Icon/CloudLightning/index.ts',
    'src/components/Icon/CloudOff/index.ts',
    'src/components/Icon/CloudRain/index.ts',
    'src/components/Icon/CloudSnow/index.ts',
    'src/components/Icon/Cloud/index.ts',
    'src/components/Icon/Code/index.ts',
    'src/components/Icon/Codepen/index.ts',
    'src/components/Icon/Codesandbox/index.ts',
    'src/components/Icon/Coffee/index.ts',
    'src/components/Icon/Columns/index.ts',
    'src/components/Icon/Command/index.ts',
    'src/components/Icon/Compass/index.ts',
    'src/components/Icon/Copy/index.ts',
    'src/components/Icon/CornerDownLeft/index.ts',
    'src/components/Icon/CornerDownRight/index.ts',
    'src/components/Icon/CornerLeftDown/index.ts',
    'src/components/Icon/CornerLeftUp/index.ts',
    'src/components/Icon/CornerRightDown/index.ts',
    'src/components/Icon/CornerRightUp/index.ts',
    'src/components/Icon/CornerUpLeft/index.ts',
    'src/components/Icon/CornerUpRight/index.ts',
    'src/components/Icon/Cpu/index.ts',
    'src/components/Icon/CreditCard/index.ts',
    'src/components/Icon/Crop/index.ts',
    'src/components/Icon/Crosshair/index.ts',
    'src/components/Icon/Database/index.ts',
    'src/components/Icon/Delete/index.ts',
    'src/components/Icon/Disc/index.ts',
    'src/components/Icon/DivideCircle/index.ts',
    'src/components/Icon/DivideSquare/index.ts',
    'src/components/Icon/Divide/index.ts',
    'src/components/Icon/DollarSign/index.ts',
    'src/components/Icon/DownloadCloud/index.ts',
    'src/components/Icon/Download/index.ts',
    'src/components/Icon/Dribbble/index.ts',
    'src/components/Icon/Droplet/index.ts',
    'src/components/Icon/Edit2/index.ts',
    'src/components/Icon/Edit3/index.ts',
    'src/components/Icon/Edit/index.ts',
    'src/components/Icon/ExternalLink/index.ts',
    'src/components/Icon/EyeOff/index.ts',
    'src/components/Icon/Eye/index.ts',
    'src/components/Icon/Facebook/index.ts',
    'src/components/Icon/FastForward/index.ts',
    'src/components/Icon/Feather/index.ts',
    'src/components/Icon/Figma/index.ts',
    'src/components/Icon/FileMinus/index.ts',
    'src/components/Icon/FilePlus/index.ts',
    'src/components/Icon/FileText/index.ts',
    'src/components/Icon/File/index.ts',
    'src/components/Icon/Film/index.ts',
    'src/components/Icon/Filter/index.ts',
    'src/components/Icon/Flag/index.ts',
    'src/components/Icon/FolderMinus/index.ts',
    'src/components/Icon/FolderPlus/index.ts',
    'src/components/Icon/Folder/index.ts',
    'src/components/Icon/Framer/index.ts',
    'src/components/Icon/Frown/index.ts',
    'src/components/Icon/Gift/index.ts',
    'src/components/Icon/GitBranch/index.ts',
    'src/components/Icon/GitCommit/index.ts',
    'src/components/Icon/GitMerge/index.ts',
    'src/components/Icon/GitPullRequest/index.ts',
    'src/components/Icon/Github/index.ts',
    'src/components/Icon/Gitlab/index.ts',
    'src/components/Icon/Globe/index.ts',
    'src/components/Icon/Grid/index.ts',
    'src/components/Icon/HardDrive/index.ts',
    'src/components/Icon/Hash/index.ts',
    'src/components/Icon/Headphones/index.ts',
    'src/components/Icon/Heart/index.ts',
    'src/components/Icon/HelpCircle/index.ts',
    'src/components/Icon/Hexagon/index.ts',
    'src/components/Icon/Home/index.ts',
    'src/components/Icon/Image/index.ts',
    'src/components/Icon/Inbox/index.ts',
    'src/components/Icon/Info/index.ts',
    'src/components/Icon/Instagram/index.ts',
    'src/components/Icon/Italic/index.ts',
    'src/components/Icon/Key/index.ts',
    'src/components/Icon/Layers/index.ts',
    'src/components/Icon/Layout/index.ts',
    'src/components/Icon/LifeBuoy/index.ts',
    'src/components/Icon/Link2/index.ts',
    'src/components/Icon/Link/index.ts',
    'src/components/Icon/Linkedin/index.ts',
    'src/components/Icon/List/index.ts',
    'src/components/Icon/Loader/index.ts',
    'src/components/Icon/Lock/index.ts',
    'src/components/Icon/LogIn/index.ts',
    'src/components/Icon/LogOut/index.ts',
    'src/components/Icon/Mail/index.ts',
    'src/components/Icon/MapPin/index.ts',
    'src/components/Icon/Map/index.ts',
    'src/components/Icon/Maximize2/index.ts',
    'src/components/Icon/Maximize/index.ts',
    'src/components/Icon/Meh/index.ts',
    'src/components/Icon/Menu/index.ts',
    'src/components/Icon/MessageCircle/index.ts',
    'src/components/Icon/MessageSquare/index.ts',
    'src/components/Icon/MicOff/index.ts',
    'src/components/Icon/Mic/index.ts',
    'src/components/Icon/Minimize2/index.ts',
    'src/components/Icon/Minimize/index.ts',
    'src/components/Icon/MinusCircle/index.ts',
    'src/components/Icon/MinusSquare/index.ts',
    'src/components/Icon/Minus/index.ts',
    'src/components/Icon/Monitor/index.ts',
    'src/components/Icon/Moon/index.ts',
    'src/components/Icon/MoreHorizontal/index.ts',
    'src/components/Icon/MoreVertical/index.ts',
    'src/components/Icon/MousePointer/index.ts',
    'src/components/Icon/Move/index.ts',
    'src/components/Icon/Music/index.ts',
    'src/components/Icon/Navigation2/index.ts',
    'src/components/Icon/Navigation/index.ts',
    'src/components/Icon/Octagon/index.ts',
    'src/components/Icon/Package/index.ts',
    'src/components/Icon/Paperclip/index.ts',
    'src/components/Icon/PauseCircle/index.ts',
    'src/components/Icon/Pause/index.ts',
    'src/components/Icon/PenTool/index.ts',
    'src/components/Icon/Percent/index.ts',
    'src/components/Icon/PhoneCall/index.ts',
    'src/components/Icon/PhoneForwarded/index.ts',
    'src/components/Icon/PhoneIncoming/index.ts',
    'src/components/Icon/PhoneMissed/index.ts',
    'src/components/Icon/PhoneOff/index.ts',
    'src/components/Icon/PhoneOutgoing/index.ts',
    'src/components/Icon/Phone/index.ts',
    'src/components/Icon/PieChart/index.ts',
    'src/components/Icon/PlayCircle/index.ts',
    'src/components/Icon/Play/index.ts',
    'src/components/Icon/PlusCircle/index.ts',
    'src/components/Icon/PlusSquare/index.ts',
    'src/components/Icon/Plus/index.ts',
    'src/components/Icon/Pocket/index.ts',
    'src/components/Icon/Power/index.ts',
    'src/components/Icon/Printer/index.ts',
    'src/components/Icon/Radio/index.ts',
    'src/components/Icon/RefreshCcw/index.ts',
    'src/components/Icon/RefreshCw/index.ts',
    'src/components/Icon/Repeat/index.ts',
    'src/components/Icon/Rewind/index.ts',
    'src/components/Icon/RotateCcw/index.ts',
    'src/components/Icon/RotateCw/index.ts',
    'src/components/Icon/Rss/index.ts',
    'src/components/Icon/Save/index.ts',
    'src/components/Icon/Scissors/index.ts',
    'src/components/Icon/Search/index.ts',
    'src/components/Icon/Send/index.ts',
    'src/components/Icon/Server/index.ts',
    'src/components/Icon/Settings/index.ts',
    'src/components/Icon/Share2/index.ts',
    'src/components/Icon/Share/index.ts',
    'src/components/Icon/ShieldOff/index.ts',
    'src/components/Icon/Shield/index.ts',
    'src/components/Icon/ShoppingBag/index.ts',
    'src/components/Icon/ShoppingCart/index.ts',
    'src/components/Icon/Shuffle/index.ts',
    'src/components/Icon/Sidebar/index.ts',
    'src/components/Icon/SkipBack/index.ts',
    'src/components/Icon/SkipForward/index.ts',
    'src/components/Icon/Slack/index.ts',
    'src/components/Icon/Slash/index.ts',
    'src/components/Icon/Sliders/index.ts',
    'src/components/Icon/Smartphone/index.ts',
    'src/components/Icon/Smile/index.ts',
    'src/components/Icon/Speaker/index.ts',
    'src/components/Icon/Square/index.ts',
    'src/components/Icon/Star/index.ts',
    'src/components/Icon/StopCircle/index.ts',
    'src/components/Icon/Sun/index.ts',
    'src/components/Icon/Sunrise/index.ts',
    'src/components/Icon/Sunset/index.ts',
    'src/components/Icon/Tablet/index.ts',
    'src/components/Icon/Tag/index.ts',
    'src/components/Icon/Target/index.ts',
    'src/components/Icon/Terminal/index.ts',
    'src/components/Icon/Thermometer/index.ts',
    'src/components/Icon/ThumbsDown/index.ts',
    'src/components/Icon/ThumbsUp/index.ts',
    'src/components/Icon/ToggleLeft/index.ts',
    'src/components/Icon/ToggleRight/index.ts',
    'src/components/Icon/Tool/index.ts',
    'src/components/Icon/Trash2/index.ts',
    'src/components/Icon/Trash/index.ts',
    'src/components/Icon/Trello/index.ts',
    'src/components/Icon/TrendingDown/index.ts',
    'src/components/Icon/TrendingUp/index.ts',
    'src/components/Icon/Triangle/index.ts',
    'src/components/Icon/Truck/index.ts',
    'src/components/Icon/Tv/index.ts',
    'src/components/Icon/Twitch/index.ts',
    'src/components/Icon/Twitter/index.ts',
    'src/components/Icon/Type/index.ts',
    'src/components/Icon/Umbrella/index.ts',
    'src/components/Icon/Underline/index.ts',
    'src/components/Icon/Unlock/index.ts',
    'src/components/Icon/UploadCloud/index.ts',
    'src/components/Icon/Upload/index.ts',
    'src/components/Icon/UserCheck/index.ts',
    'src/components/Icon/UserMinus/index.ts',
    'src/components/Icon/UserPlus/index.ts',
    'src/components/Icon/UserX/index.ts',
    'src/components/Icon/User/index.ts',
    'src/components/Icon/Users/index.ts',
    'src/components/Icon/VideoOff/index.ts',
    'src/components/Icon/Video/index.ts',
    'src/components/Icon/Voicemail/index.ts',
    'src/components/Icon/Volume1/index.ts',
    'src/components/Icon/Volume2/index.ts',
    'src/components/Icon/VolumeX/index.ts',
    'src/components/Icon/Volume/index.ts',
    'src/components/Icon/Watch/index.ts',
    'src/components/Icon/WifiOff/index.ts',
    'src/components/Icon/Wifi/index.ts',
    'src/components/Icon/Wind/index.ts',
    'src/components/Icon/XCircle/index.ts',
    'src/components/Icon/XOctagon/index.ts',
    'src/components/Icon/XSquare/index.ts',
    'src/components/Icon/X/index.ts',
    'src/components/Icon/Youtube/index.ts',
    'src/components/Icon/ZapOff/index.ts',
    'src/components/Icon/Zap/index.ts',
    'src/components/Icon/ZoomIn/index.ts',
    'src/components/Icon/ZoomOut/index.ts',
  ],
  output: [
    {
      dir: 'build',
      format: 'cjs',
      sourcemap: true,
    },
  ],
  preserveModules: true, // Important if we want to code split
  plugins: [
    peerDepsExternal(),
    commonjs(),
    typescript({ useTsconfigDeclarationDir: true }),
    scss({
      // Run postcss processor before output
      processor: (css) => postcss([autoprefixer({})]),
      // Output both minified and uncompressed css
      output: function (styles, styleNodes) {
        fs.mkdir(__dirname + '\\build\\styles', { recursive: true }, (err) => {
          if (err) throw err;
        });

        fs.writeFileSync(__dirname + '\\build\\styles\\main.css', styles);
        const minifiedStyles = new CleanCss().minify(styles).styles;
        fs.writeFileSync(
          __dirname + '\\build\\styles\\main.min.css',
          minifiedStyles
        );
      },
    }),
    copy({
      targets: [
        {
          src: 'src/variables.scss',
          dest: 'build',
          rename: 'variables.scss',
        },
        {
          src: 'src/typography.scss',
          dest: 'build',
          rename: 'typography.scss',
        },
      ],
    }),
  ],
};
