
    // this file was auto generated by python script
    // this icon was sourced from feather icons 4.2.8
    import React from 'react';
    const ChevronDown = () => (
      <>
        <polyline points="6 9 12 15 18 9"></polyline>
      </>
    );
    export default ChevronDown;
    