
    // this file was auto generated by python script
    // this icon was sourced from feather icons 4.2.8
    import React from 'react';
    const ChevronLeft = () => (
      <>
        <polyline points="15 18 9 12 15 6"></polyline>
      </>
    );
    export default ChevronLeft;
    