
    // this file was auto generated by python script
    // this icon was sourced from feather icons 4.2.8
    import React from 'react';
    const Circle = () => (
      <>
        <circle cx="12" cy="12" r="10"></circle>
      </>
    );
    export default Circle;
    