
    // this file was auto generated by python script
    // this icon was sourced from feather icons 4.2.8
    import React from 'react';
    const Minus = () => (
      <>
        <line x1="5" y1="12" x2="19" y2="12"></line>
      </>
    );
    export default Minus;
    