
    // this file was auto generated by python script
    // this icon was sourced from feather icons 4.2.8
    import React from 'react';
    const Droplet = () => (
      <>
        <path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z"></path>
      </>
    );
    export default Droplet;
    